#!/bin/bash

# IAM 项目源码根目录
IAM_ROOT=$(dirname "${BASH_SOURCE[0]}")/../..

# 生成文件存放目录
LOCAL_OUTPUT_ROOT="${IAM_ROOT}/${OUT_DIR:-_output}"

# 设置统一的密码，方便记忆
readonly PASSWORD=${PASSWORD:-'iam59!z$'}

# 环境配置
readonly APP_ENV=${APP_ENV:-development}  # development, test, production
readonly GO_ENV=${GO_ENV:-${APP_ENV}}     # 兼容GO_ENV

# Linux系统 going 用户
readonly LINUX_USERNAME=${LINUX_USERNAME:-going}
# Linux root & going 用户密码
readonly LINUX_PASSWORD=${LINUX_PASSWORD:-${PASSWORD}}

# 设置安装目录
readonly INSTALL_DIR=${INSTALL_DIR:-/tmp/installation}
mkdir -p ${INSTALL_DIR}
readonly ENV_FILE=${IAM_ROOT}/scripts/install/environment.sh

# MariaDB 配置信息
readonly MARIADB_ADMIN_USERNAME=${MARIADB_ADMIN_USERNAME:-root} # MariaDB root 用户
readonly MARIADB_ADMIN_PASSWORD=${MARIADB_ADMIN_PASSWORD:-${PASSWORD}} # MariaDB root 用户密码
readonly MARIADB_HOST=${MARIADB_HOST:-127.0.0.1:3306} # MariaDB 主机地址
readonly MARIADB_DATABASE=${MARIADB_DATABASE:-iam} # MariaDB iam 应用使用的数据库名
readonly MARIADB_USERNAME=${MARIADB_USERNAME:-iam} # iam 数据库用户名
readonly MARIADB_PASSWORD=${MARIADB_PASSWORD:-${PASSWORD}} # iam 数据库密码

# Redis 配置信息
readonly REDIS_HOST=${REDIS_HOST:-127.0.0.1} # Redis 主机地址
readonly REDIS_PORT=${REDIS_PORT:-6379} # Redis 监听端口
readonly REDIS_USERNAME=${REDIS_USERNAME:-''} # Redis 用户名
readonly REDIS_PASSWORD=${REDIS_PASSWORD:-${PASSWORD}} # Redis 密码

# MongoDB 配置
readonly MONGO_ADMIN_USERNAME=${MONGO_ADMIN_USERNAME:-root} # MongoDB root 用户
readonly MONGO_ADMIN_PASSWORD=${MONGO_ADMIN_PASSWORD:-${PASSWORD}} # MongoDB root 用户密码
readonly MONGO_HOST=${MONGO_HOST:-127.0.0.1} # MongoDB 地址
readonly MONGO_PORT=${MONGO_PORT:-27017} # MongoDB 端口
readonly MONGO_USERNAME=${MONGO_USERNAME:-iam} # MongoDB 用户名
readonly MONGO_PASSWORD=${MONGO_PASSWORD:-${PASSWORD}} # MongoDB 密码

# iam 配置
readonly IAM_DATA_DIR=${IAM_DATA_DIR:-/data/iam} # iam 各组件数据目录
readonly IAM_INSTALL_DIR=${IAM_INSTALL_DIR:-/opt/iam} # iam 安装文件存放目录
readonly IAM_CONFIG_DIR=${IAM_CONFIG_DIR:-/etc/iam} # iam 配置文件存放目录
readonly IAM_LOG_DIR=${IAM_LOG_DIR:-/var/log/iam} # iam 日志文件存放目录
readonly CA_FILE=${CA_FILE:-${IAM_CONFIG_DIR}/cert/ca.pem} # CA

# iam-apiserver 配置
readonly IAM_APISERVER_HOST=${IAM_APISERVER_HOST:-127.0.0.1} # iam-apiserver 部署机器 IP 地址
readonly IAM_APISERVER_GRPC_BIND_ADDRESS=${IAM_APISERVER_GRPC_BIND_ADDRESS:-0.0.0.0}
readonly IAM_APISERVER_GRPC_BIND_PORT=${IAM_APISERVER_GRPC_BIND_PORT:-8081}
readonly IAM_APISERVER_INSECURE_BIND_ADDRESS=${IAM_APISERVER_INSECURE_BIND_ADDRESS:-127.0.0.1}
readonly IAM_APISERVER_INSECURE_BIND_PORT=${IAM_APISERVER_INSECURE_BIND_PORT:-8080}
readonly IAM_APISERVER_SECURE_BIND_ADDRESS=${IAM_APISERVER_SECURE_BIND_ADDRESS:-0.0.0.0}
readonly IAM_APISERVER_SECURE_BIND_PORT=${IAM_APISERVER_SECURE_BIND_PORT:-8443}
readonly IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE:-${IAM_CONFIG_DIR}/cert/iam-apiserver.pem}
readonly IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${IAM_CONFIG_DIR}/cert/iam-apiserver-key.pem}

# iam-authz-server 配置
readonly IAM_AUTHZ_SERVER_HOST=${IAM_AUTHZ_SERVER_HOST:-127.0.0.1} # iam-authz-server 部署机器 IP 地址
readonly IAM_AUTHZ_SERVER_INSECURE_BIND_ADDRESS=${IAM_AUTHZ_SERVER_INSECURE_BIND_ADDRESS:-127.0.0.1}
readonly IAM_AUTHZ_SERVER_INSECURE_BIND_PORT=${IAM_AUTHZ_SERVER_INSECURE_BIND_PORT:-9090}
readonly IAM_AUTHZ_SERVER_SECURE_BIND_ADDRESS=${IAM_AUTHZ_SERVER_SECURE_BIND_ADDRESS:-0.0.0.0}
readonly IAM_AUTHZ_SERVER_SECURE_BIND_PORT=${IAM_AUTHZ_SERVER_SECURE_BIND_PORT:-9443}
readonly IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE=${IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE:-${IAM_CONFIG_DIR}/cert/iam-authz-server.pem}
readonly IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE=${IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE:-${IAM_CONFIG_DIR}/cert/iam-authz-server-key.pem}
readonly IAM_AUTHZ_SERVER_CLIENT_CA_FILE=${IAM_AUTHZ_SERVER_CLIENT_CA_FILE:-${CA_FILE}}
readonly IAM_AUTHZ_SERVER_RPCSERVER=${IAM_AUTHZ_SERVER_RPCSERVER:-${IAM_APISERVER_HOST}:${IAM_APISERVER_GRPC_BIND_PORT}}

# iam-pump 配置
readonly IAM_PUMP_HOST=${IAM_PUMP_HOST:-127.0.0.1} # iam-pump 部署机器 IP 地址
readonly IAM_PUMP_COLLECTION_NAME=${IAM_PUMP_COLLECTION_NAME:-iam_analytics}
readonly IAM_PUMP_MONGO_URL=${IAM_PUMP_MONGO_URL:-mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${IAM_PUMP_COLLECTION_NAME}?authSource=${IAM_PUMP_COLLECTION_NAME}}

# iam-watcher配置
readonly IAM_WATCHER_HOST=${IAM_WATCHER_HOST:-127.0.0.1} # iam-watcher 部署机器 IP 地址

# iamctl 配置
readonly CONFIG_USER_USERNAME=${CONFIG_USER_USERNAME:-admin}
readonly CONFIG_USER_PASSWORD=${CONFIG_USER_PASSWORD:-Admin@2021}
readonly CONFIG_USER_CLIENT_CERTIFICATE=${CONFIG_USER_CLIENT_CERTIFICATE:-${HOME}/.iam/cert/admin.pem}
readonly CONFIG_USER_CLIENT_KEY=${CONFIG_USER_CLIENT_KEY:-${HOME}/.iam/cert/admin-key.pem}
readonly CONFIG_SERVER_ADDRESS=${CONFIG_SERVER_ADDRESS:-${IAM_APISERVER_HOST}:${IAM_APISERVER_SECURE_BIND_PORT}}
readonly CONFIG_SERVER_CERTIFICATE_AUTHORITY=${CONFIG_SERVER_CERTIFICATE_AUTHORITY:-${CA_FILE}}

# 环境特定配置覆盖
# 开发环境配置
if [[ "${APP_ENV}" == "development" ]]; then
    # 开发环境使用本地地址和宽松配置
    readonly IAM_APISERVER_HOST=${IAM_APISERVER_HOST:-127.0.0.1}
    readonly MARIADB_HOST=${MARIADB_HOST:-127.0.0.1:3306}
    readonly REDIS_HOST=${REDIS_HOST:-127.0.0.1}
    readonly MONGO_HOST=${MONGO_HOST:-127.0.0.1}
    readonly IAM_LOG_DIR=${IAM_LOG_DIR:-/tmp/iam/logs}
    readonly IAM_DATA_DIR=${IAM_DATA_DIR:-/tmp/iam/data}
    
# 测试环境配置
elif [[ "${APP_ENV}" == "test" ]]; then
    # 测试环境使用测试服务器
    readonly IAM_APISERVER_HOST=${IAM_APISERVER_HOST:-test-api.example.com}
    readonly MARIADB_HOST=${MARIADB_HOST:-test-db.example.com:3306}
    readonly REDIS_HOST=${REDIS_HOST:-test-redis.example.com}
    readonly MONGO_HOST=${MONGO_HOST:-test-mongo.example.com}
    readonly IAM_LOG_DIR=${IAM_LOG_DIR:-/var/log/iam-test}
    
# 生产环境配置
elif [[ "${APP_ENV}" == "production" ]]; then
    # 生产环境使用生产服务器和高可用配置
    readonly IAM_APISERVER_HOST=${IAM_APISERVER_HOST:-api.iam-production.com}
    readonly MARIADB_HOST=${MARIADB_HOST:-mariadb-cluster.iam-production.com:3306}
    readonly REDIS_HOST=${REDIS_HOST:-redis-cluster.iam-production.com}
    readonly MONGO_HOST=${MONGO_HOST:-mongo-cluster.iam-production.com}
    readonly IAM_LOG_DIR=${IAM_LOG_DIR:-/var/log/iam}
    
    # 生产环境安全强化
    readonly PASSWORD=${PASSWORD:-'MustChangeThisInProduction!'}
    readonly LINUX_PASSWORD=${LINUX_PASSWORD:-'ProductionLinuxPassword!'}
    readonly MARIADB_ADMIN_PASSWORD=${MARIADB_ADMIN_PASSWORD:-'ProductionDBRootPassword!'}
    readonly MARIADB_PASSWORD=${MARIADB_PASSWORD:-'ProductionDBPassword!'}
    readonly REDIS_PASSWORD=${REDIS_PASSWORD:-'ProductionRedisPassword!'}
    readonly MONGO_ADMIN_PASSWORD=${MONGO_ADMIN_PASSWORD:-'ProductionMongoRootPassword!'}
    readonly MONGO_PASSWORD=${MONGO_PASSWORD:-'ProductionMongoPassword!'}
fi

# 环境变量导出
export APP_ENV GO_ENV
export PASSWORD LINUX_USERNAME LINUX_PASSWORD
export INSTALL_DIR ENV_FILE
export MARIADB_ADMIN_USERNAME MARIADB_ADMIN_PASSWORD MARIADB_HOST MARIADB_DATABASE MARIADB_USERNAME MARIADB_PASSWORD
export REDIS_HOST REDIS_PORT REDIS_USERNAME REDIS_PASSWORD
export MONGO_ADMIN_USERNAME MONGO_ADMIN_PASSWORD MONGO_HOST MONGO_PORT MONGO_USERNAME MONGO_PASSWORD
export IAM_DATA_DIR IAM_INSTALL_DIR IAM_CONFIG_DIR IAM_LOG_DIR CA_FILE
export IAM_APISERVER_HOST IAM_APISERVER_GRPC_BIND_ADDRESS IAM_APISERVER_GRPC_BIND_PORT
export IAM_APISERVER_INSECURE_BIND_ADDRESS IAM_APISERVER_INSECURE_BIND_PORT
export IAM_APISERVER_SECURE_BIND_ADDRESS IAM_APISERVER_SECURE_BIND_PORT
export IAM_APISERVER_SECURE_TLS_CERT_KEY_CERT_FILE IAM_APISERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE
export IAM_AUTHZ_SERVER_HOST IAM_AUTHZ_SERVER_INSECURE_BIND_ADDRESS IAM_AUTHZ_SERVER_INSECURE_BIND_PORT
export IAM_AUTHZ_SERVER_SECURE_BIND_ADDRESS IAM_AUTHZ_SERVER_SECURE_BIND_PORT
export IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE IAM_AUTHZ_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE
export IAM_AUTHZ_SERVER_CLIENT_CA_FILE IAM_AUTHZ_SERVER_RPCSERVER
export IAM_PUMP_HOST IAM_PUMP_COLLECTION_NAME IAM_PUMP_MONGO_URL
export IAM_WATCHER_HOST
export CONFIG_USER_USERNAME CONFIG_USER_PASSWORD CONFIG_USER_CLIENT_CERTIFICATE CONFIG_USER_CLIENT_KEY
export CONFIG_SERVER_ADDRESS CONFIG_SERVER_CERTIFICATE_AUTHORITY

# 输出当前环境信息
echo "当前运行环境: ${APP_ENV}"
echo "API服务器: ${IAM_APISERVER_HOST}"
echo "数据库服务器: ${MARIADB_HOST}"
echo "日志目录: ${IAM_LOG_DIR}"