global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alerts.yml

scrape_configs:
  # 主要监控端点 - 从 /metrics 拉取真实数据
  - job_name: 'user-service-metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          env: 'development'
          service: 'user-service'

  # 可选：也可以监控测试端点（用于调试）
  - job_name: 'user-service-test'
    scrape_interval: 30s      # 测试端点抓取间隔可以长一些
    scrape_timeout: 5s
    metrics_path: '/test-all-metrics'  # 测试端点
    scheme: 'http'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          env: 'development'
          service: 'user-service-test'

  # 监控 Prometheus 自身
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 监控 MySQL
  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']

  # 监控 Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']