apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kafka-partitions-no-owner
  labels:
    role: alert-rules
spec:
  groups:
    - name: kafka.rules
      rules:
        - alert: KafkaPartitionsWithoutConsumer
          expr: |
            sum(kafka_partitions_without_consumer) by (topic, group) > 0
          for: 1m
          labels:
            severity: critical
            service: kafka
          annotations:
            summary: "Kafka topic {{ $labels.topic }} has partitions without consumer (group={{ $labels.group }})"
            description: |
              在过去 1 分钟内，主题 {{ $labels.topic }} 对应的消费者组 {{ $labels.group }} 存在未被任何消费者持有的分区。
              这通常意味着：
                * 消费者实例没有正确启动或没有成功加入消费组；
                * 消费者因错误/崩溃退出；
                * 消费者组配置或网络导致部分分区没有 owner。
              建议检查服务日志、consumer group 列表以及该主题的分区分配状态。
            runbook: |
              1. 查看 Prometheus 中相关 metrics：
                 - kafka_partitions_without_consumer{topic="<topic>",group="<group>"}
                 - kafka_consumer_group_instances{group="<group>"}
                 - kafka_consumer_lag{topic="<topic>",group="<group>"}
              2. 在 Kafka 集群中检查 consumer group：
                 kafka-consumer-groups.sh --bootstrap-server <broker> --describe --group <group>
              3. 检查目标服务日志，确认消费者是否启动并成功加入消费组。
              4. 如果是部署/实例数量问题，考虑横向扩容消费者实例或重启有问题的实例。
              5. 如需快速清理 backlog，可在确认业务允许的前提下增加临时消费者或回退到 manual reprocess 流程。
